name: ci

on:
  release:
    types: [published]
    tag:
      - v1.*

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: kaung4410/randnumimg:v1.1

      # -
      #   name: Post message on slack
      #   uses: bluenovaio/action-slack@main
      #   with:
      #     username: ""
      #     icon_emoji: ":robot_face:"
      #     text:  "Name: Kaung Hein\nMatriculation: A0249490W\nEmail: <outlook.com|E0941683@U.NUS.EDU> \nRepo: <https://github.com/Dante-Black/randnum.git|git@github.com:Dante-Black/randnum.git>\nImage name: \nImage url: "
      #     webhook_url: ${{ secrets.SLACK_WEBHOOK }}
